SavvyPortfolioBundle:
    resource: "@SavvyPortfolioBundle/Controller/"
    type:     annotation

SavvyStaticBundle:
    resource: "@SavvyStaticBundle/Controller/"
    type:     annotation

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
