SavvyContactExtensionBundle:
    resource: "@SavvyContactExtensionBundle/Controller/"
    type:     annotation
    prefix:   /

SavvyPortfolioBundle:
    resource: "@SavvyPortfolioBundle/Controller/"
    type:     annotation

SavvyStaticBundle:
    resource: "@SavvyStaticBundle/Controller/"
    type:     annotation

OxygenContactBundle:
    resource: "@OxygenContactBundle/Controller/"
    type:     annotation

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
